import {
  Injectable,
  CanActivate,
  ExecutionContext,
  UnauthorizedException,
  Logger,
} from '@nestjs/common';
import { AuthService } from '../auth.service';
import { CognitoJwtService } from '../cognito-jwt.service';
import * as jwt from 'jsonwebtoken';

/**
 * JwtAuthGuard with optional Cognito JWT support
 * 
 * This guard supports TWO types of JWT tokens:
 * 1. Custom JWT tokens (existing) - Generated by AuthService after multi-provider authentication
 * 2. Cognito JWT tokens (new) - Issued directly by AWS Cognito user pools
 * 
 * BACKWARD COMPATIBILITY:
 * All existing custom JWT authentication flows remain unchanged and continue to work.
 * The guard automatically detects the token type and routes to the appropriate verification service.
 * 
 * TOKEN DETECTION LOGIC:
 * - Cognito JWTs have specific claims: 'iss' (issuer) contains 'cognito-idp', and 'token_use' exists
 * - Custom JWTs only have 'userId' claim and are signed with JWT_SECRET
 * 
 * ROUTING:
 * - Cognito JWTs → CognitoJwtService.verifyCognitoToken()
 * - Custom JWTs → AuthService.validateAccessToken()
 */
@Injectable()
export class JwtAuthGuard implements CanActivate {
  private readonly logger = new Logger(JwtAuthGuard.name);

  constructor(
    private readonly authService: AuthService,
    private readonly cognitoJwtService: CognitoJwtService,
  ) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const request = context.switchToHttp().getRequest();
    const authHeader = request.headers.authorization;

    if (!authHeader) {
      throw new UnauthorizedException('No authorization header');
    }

    const [bearer, token] = authHeader.split(' ');

    if (bearer !== 'Bearer' || !token) {
      throw new UnauthorizedException('Invalid authorization header format');
    }

    try {
      // Detect token type by decoding without verification
      const tokenType = this.detectTokenType(token);

      if (tokenType === 'cognito') {
        // Route to Cognito JWT verification
        this.logger.debug('Detected Cognito JWT, routing to CognitoJwtService');
        return await this.verifyCognitoToken(request, token);
      } else {
        // Route to custom JWT verification (existing flow)
        this.logger.debug('Detected custom JWT, routing to AuthService');
        return await this.verifyCustomToken(request, token);
      }
    } catch (error) {
      // Error handling for both token types
      if (error instanceof UnauthorizedException) {
        throw error;
      }
      
      this.logger.error('Token verification failed', {
        errorName: error.name,
        errorMessage: error.message,
      });
      throw new UnauthorizedException('Invalid or expired token');
    }
  }

  /**
   * Detect whether the token is a Cognito JWT or custom JWT
   * Cognito JWTs have specific claims that differentiate them:
   * - 'iss' (issuer) contains 'cognito-idp'
   * - 'token_use' claim exists (either 'id' or 'access')
   * 
   * @param token - JWT token string
   * @returns 'cognito' | 'custom'
   */
  private detectTokenType(token: string): 'cognito' | 'custom' {
    try {
      // Decode without verification to inspect claims
      const decoded = jwt.decode(token, { complete: true });

      if (!decoded || typeof decoded === 'string') {
        // Malformed token, default to custom JWT for backward compatibility
        return 'custom';
      }

      const payload = decoded.payload as any;

      // Check for Cognito-specific claims
      const hasCognitoIssuer =
        payload.iss &&
        typeof payload.iss === 'string' &&
        payload.iss.includes('cognito-idp');

      const hasTokenUse = payload.token_use !== undefined;

      if (hasCognitoIssuer && hasTokenUse) {
        return 'cognito';
      }

      // Default to custom JWT
      return 'custom';
    } catch (error) {
      // If decoding fails, assume custom JWT for backward compatibility
      this.logger.debug('Token decode failed during type detection, defaulting to custom JWT');
      return 'custom';
    }
  }

  /**
   * Verify Cognito JWT token using CognitoJwtService
   * Extracts userId from 'sub' claim and loads user from database
   * 
   * @param request - Express request object
   * @param token - Cognito JWT token
   * @returns true if verification succeeds
   * @throws UnauthorizedException if verification fails
   */
  private async verifyCognitoToken(
    request: any,
    token: string,
  ): Promise<boolean> {
    try {
      // Verify Cognito token using JWKS
      const cognitoPayload = await this.cognitoJwtService.verifyCognitoToken(token);

      // Extract userId from 'sub' claim
      const userId = cognitoPayload.sub;

      // Load user from database using the userId
      const user = await this.authService.getUserById(userId);

      request.user = user;
      return true;
    } catch (error) {
      this.logger.warn('Cognito JWT verification failed', {
        errorMessage: error.message,
      });
      
      // Re-throw UnauthorizedException from CognitoJwtService
      if (error instanceof UnauthorizedException) {
        throw error;
      }
      
      throw new UnauthorizedException('Invalid Cognito token');
    }
  }

  /**
   * Verify custom JWT token using AuthService (existing flow)
   * Maintains backward compatibility with all existing authentication flows
   * 
   * @param request - Express request object
   * @param token - Custom JWT token
   * @returns true if verification succeeds
   * @throws UnauthorizedException if verification fails
   */
  private async verifyCustomToken(
    request: any,
    token: string,
  ): Promise<boolean> {
    try {
      // Use existing AuthService validation (unchanged)
      const user = await this.authService.validateAccessToken(token);
      request.user = user;
      return true;
    } catch (error) {
      this.logger.warn('Custom JWT verification failed', {
        errorMessage: error.message,
      });
      
      // Re-throw UnauthorizedException to preserve error messages
      if (error instanceof UnauthorizedException) {
        throw error;
      }
      
      throw new UnauthorizedException('Invalid or expired token');
    }
  }
}
