name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-079d51280d1964117" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["sudo -u ssm-user bash -c \"export HOME=/home/ssm-user && export PM2_HOME=/home/ssm-user/.pm2 && export PATH=/usr/local/bin:/usr/bin:/bin && cd /home/ssm-user/unifesto/app && git stash && git pull origin main && npm ci --omit=dev --legacy-peer-deps && npx prisma generate && npx prisma migrate deploy && ./node_modules/.bin/nest build && pm2 restart unifesto --update-env && pm2 save\""]}' \
            --region ap-south-1
          echo "Deploy command sent to EC2 successfully"
